/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MetadataIndexRouteImport } from './routes/metadata/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GalleryImageIdRouteImport } from './routes/gallery/$imageId'
import { Route as WorkspaceProjectIdRouteRouteImport } from './routes/workspace/$projectId/route'
import { Route as WorkspaceProjectIdIndexRouteImport } from './routes/workspace/$projectId/index'
import { Route as WorkspaceProjectIdScenesSceneIdRouteImport } from './routes/workspace/$projectId/scenes/$sceneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataIndexRoute = MetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryImageIdRoute = GalleryImageIdRouteImport.update({
  id: '/gallery/$imageId',
  path: '/gallery/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdRouteRoute = WorkspaceProjectIdRouteRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdIndexRoute = WorkspaceProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceProjectIdRouteRoute,
} as any)
const WorkspaceProjectIdScenesSceneIdRoute =
  WorkspaceProjectIdScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => WorkspaceProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteRouteWithChildren
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery': typeof GalleryIndexRoute
  '/metadata': typeof MetadataIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteRouteWithChildren
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/gallery/': typeof GalleryIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace/$projectId'
    | '/gallery/$imageId'
    | '/gallery/'
    | '/metadata/'
    | '/settings/'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery/$imageId'
    | '/gallery'
    | '/metadata'
    | '/settings'
    | '/workspace/$projectId'
    | '/workspace/$projectId/scenes/$sceneId'
  id:
    | '__root__'
    | '/'
    | '/workspace/$projectId'
    | '/gallery/$imageId'
    | '/gallery/'
    | '/metadata/'
    | '/settings/'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceProjectIdRouteRoute: typeof WorkspaceProjectIdRouteRouteWithChildren
  GalleryImageIdRoute: typeof GalleryImageIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  MetadataIndexRoute: typeof MetadataIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/': {
      id: '/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof MetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$imageId': {
      id: '/gallery/$imageId'
      path: '/gallery/$imageId'
      fullPath: '/gallery/$imageId'
      preLoaderRoute: typeof GalleryImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId/': {
      id: '/workspace/$projectId/'
      path: '/'
      fullPath: '/workspace/$projectId/'
      preLoaderRoute: typeof WorkspaceProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectIdRouteRoute
    }
    '/workspace/$projectId/scenes/$sceneId': {
      id: '/workspace/$projectId/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/workspace/$projectId/scenes/$sceneId'
      preLoaderRoute: typeof WorkspaceProjectIdScenesSceneIdRouteImport
      parentRoute: typeof WorkspaceProjectIdRouteRoute
    }
  }
}

interface WorkspaceProjectIdRouteRouteChildren {
  WorkspaceProjectIdIndexRoute: typeof WorkspaceProjectIdIndexRoute
  WorkspaceProjectIdScenesSceneIdRoute: typeof WorkspaceProjectIdScenesSceneIdRoute
}

const WorkspaceProjectIdRouteRouteChildren: WorkspaceProjectIdRouteRouteChildren =
  {
    WorkspaceProjectIdIndexRoute: WorkspaceProjectIdIndexRoute,
    WorkspaceProjectIdScenesSceneIdRoute: WorkspaceProjectIdScenesSceneIdRoute,
  }

const WorkspaceProjectIdRouteRouteWithChildren =
  WorkspaceProjectIdRouteRoute._addFileChildren(
    WorkspaceProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceProjectIdRouteRoute: WorkspaceProjectIdRouteRouteWithChildren,
  GalleryImageIdRoute: GalleryImageIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  MetadataIndexRoute: MetadataIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
